blank_issues_enabled: false
contact_links:
  - name: Notion Build Tracker
    url: https://www.notion.so/Unidex-Startup-HQ-36a3bfee71f5812cbcd2c011e92c7f0f
    about: Check the Notion Build Tracker before opening an issue
