-- Superseded — intentionally a no-op.
--
-- This migration previously set Unsplash stock photos and hotlinked Wikimedia
-- thumbnails as college images. Both are prohibited:
--   * no stock photos / no image reused across colleges
--   * no hotlinking Wikimedia
--
-- College images now live in the `college-images` Supabase Storage bucket as
-- {college_id}.webp (licensed Commons photos, resized), with attribution in
-- colleges.image_credit / image_license / image_source_url. Where no qualifying
-- licensed photo exists, image_url is left NULL and the UI renders the
-- tier-coloured monogram placeholder.
